POST http://localhost:4100/notes
Content-Type: application/json

{
    "title": " Notice",
    "content": "Trying new notebooks app"
}

### GETTING ALL NOTES

GET http://localhost:4100/notes
Content-Type: application/json


### GETTING NOTE BY ID

GET http://localhost:4100/notes/b01f3204-8635-4d7a-a4f4-1cf5ed38c340


###
PUT http://localhost:4100/notes/update/b01f3204-8635-4d7a-a4f4-1cf5ed38c340
Content-Type: application/json

{
    "title": "First Note",
    "content": "I aced it"
}

###

DELETE http://localhost:4100/notes/delete/0b5b5bb2-76ff-400c-8bf5-602329cf31ab
Content-Type: application/json