POST http://localhost:4100/notes
Content-Type: application/json

{
    "title": " Note 3",
    "content": "Trying new notebooks app",
    "createdAt": "9/2/2024"
}

### GETTING ALL NOTES

GET http://localhost:4100/notes
Content-Type: application/json


### GETTING NOTE BY ID

GET http://localhost:4100/notes/2778c94d-8bf7-4e99-b377-805fbcf2cb42


###
PUT http://localhost:4100/notes/update/0671242c-9260-43ee-a842-7eef5cd9e5ec
Content-Type: application/json

{
    "title": "First Note",
    "content": "I aced it",
    "createdAt": "9/2/2024"
}

###

DELETE http://localhost:4100/notes/delete/333e83e1-ad39-4b36-a247-cb7dd6dca20e
Content-Type: application/json